[log]
  level = "DEBUG"

[entryPoints]
  [entryPoints.web]
    address = ":80"
    
[api]
  dashboard = true
  insecure=false

[providers.docker]
  exposedByDefault = false
  network = "traefik-global-proxy" 
